In [25]:
import pickle,json
data_path="data/nuscenes/nuscenes_infos_temporal_train.pkl"
with open(data_path,'rb') as f:
    data = pickle.load(f)
    infos = data["infos"]
    metadata = data["metadata"]
    sample = infos[0]
    # dump to json for debug
    print(sample['cams']["CAM_BACK_LEFT"]["sensor2lidar_rotation"])
    print(sample['cams']["CAM_BACK_LEFT"]["sensor2lidar_translation"])
    print(sample['gt_boxes'].shape)
    print(sample['gt_names'].shape)
    print(sample['num_lidar_pts'].shape)
    print(type(sample["can_bus"]))
    print(sample["can_bus"].shape)


        
        


[[-0.31705823  0.01989865 -0.9481973 ]
 [ 0.94807978  0.03287344 -0.31632905]
 [ 0.02487598 -0.99926142 -0.0292883 ]]
[-0.48328143  0.09404905 -0.24994862]
(69, 7)
(69,)
(69,)
<class 'numpy.ndarray'>
(18,)


In [26]:
data_path="data/nuscenes/dvscenes_infos_temporal_train.pkl"
with open(data_path,'rb') as f:
    data = pickle.load(f)
    infos = data["infos"]
    metadata = data["metadata"]
    sample = infos[0]
    # dump to json for debug
    print(sample['cams']["CAM_BACK_LEFT"]["sensor2lidar_rotation"])
    print(sample['cams']["CAM_BACK_LEFT"]["sensor2lidar_translation"])
    print(sample['gt_boxes'].shape)
    print(sample['gt_names'].shape)
    print(sample['num_lidar_pts'].shape)
    print(type(sample["can_bus"]))
    print(sample["can_bus"].shape)




[[ 0.13821602  0.70623041 -0.69435938]
 [ 0.24669676 -0.70354038 -0.66646204]
 [-0.95918561 -0.07918048 -0.2714653 ]]
[0.3993379  3.50074661 2.33663251]
(8, 7)
(8,)
(8,)
<class 'list'>
